### ISSUE TITLE
Issue while showing NN to relationship as tag

### ISSUE THREAD

**Issue by ram-sannidi** [opc-cpvp/OPC.PowerApps.PCFControls#18]
Hi,

i am looking for the exact requirement, followed your code and tried in our Dev. But its not working. id attribute and name attribute are always null. Also i have a question. could you please let me know when can i see the code which is related to existing relations?

Thanks
Ram
![Issue](https://user-images.githubusercontent.com/45936515/91418373-550b7d00-e852-11ea-8ca3-7b7fc98b68f2.PNG)

**Comment by ram-sannidi** [comment]
Also could you please let me know how to use Plugins which are part of this solution.

**Comment by joshcampbell191** [comment]
Hello @ram-sannidi,

This sounds like a configuration issue with the field. Can you please ensure that the parameters (Related Entity, Relationship Name and Relationship Entity) are properly configured? 

It should look something like this:
![Capture](https://user-images.githubusercontent.com/1784236/91445725-7a918a00-e844-11ea-9a8b-88e1946c72f5.PNG)

> could you please let me know when can i see the code which is related to existing relations?

The code that handles existing relations can be found here:
- [TagPickerComponent](https://github.com/opc-cpvp/OPC.PowerApps.PCFControls/blob/master/src/Components/TagPickerComponent/TagPickerComponent/TagPickerBaseComponent.ts#L139)
- [TagPickerGridComponent](https://github.com/opc-cpvp/OPC.PowerApps.PCFControls/blob/master/src/Components/TagPickerGridComponent/TagPickerGridComponent/TagPickerBaseComponent.ts#L178)

Finally, as for the plugin, it should automatically be registered when importing the managed / un-managed solution. The plugin registers a step on Post create of any entity. It scans the fields looking for a given prefix (TAGDATA) which indicates whether the plugin needs to create links to other entities. This allows us to link to existing entities when working with a new (versus existing) entity.

Here's what the plugin step should look like:
![Capture2](https://user-images.githubusercontent.com/1784236/91446823-efb18f00-e845-11ea-8a33-55c706784a49.PNG)

Hope this answers your questions.

Thanks,
Joshua Campbell

**Comment by ram-sannidi** [comment]
Thanks a lot for speed response.

I am unable to download the managed solution. Could you please help me where can I get it?

Also could you please tell how the plugin worked with PCF component and what should I mention in related entity and relationship entity? I mean if A has N:N relationship with B what should I mention in related entity ?

Regards
Ram

Thanks
Ram
________________________________

**Comment by joshcampbell191** [comment]
> I am unable to download the managed solution. Could you please help me where can I get it?

You can download the latest managed solution from the following URL: [https://github.com/opc-cpvp/OPC.PowerApps.PCFControls/releases/latest](https://github.com/opc-cpvp/OPC.PowerApps.PCFControls/releases/latest)

> Also could you please tell how the plugin worked with PCF component

The plugin only gets triggered after an entity is created. It then scans each of the fields of the entity for the prefix and converts the data into relationships on the field.

> what should I mention in related entity and relationship entity? I mean if A has N:N relationship with B what should I mention in related entity

You should be using the "Relationship entity name" of the relationship between your two entities.
![Relationship entity name](https://user-images.githubusercontent.com/1784236/91451641-9fd5c680-e84b-11ea-957b-f31b604a6912.png)


Regards,
Joshua Campbell

**Comment by ram-sannidi** [comment]
Hi Joshua,

My apologies for spamming your mailbox.

I doubt that below code wont work for N:N relationships:

[cid:image001.png@01D67C8D.9B3282A0]

I added relationshipName instead of relationship entity. It was throwing error when I am using relationshipEntity.

Also there is some issue with EntityMetadata it seems. I was going through Primary Attributes and could not find the attributes which were mentioned in the solution.

PrimaryNameAttribute is
[cid:image002.png@01D67C8F.99FDE850]

Primary Id Attribute is
[cid:image004.png@01D67C8F.99FDE850]

Also one question for which I am waiting for response. Sorry for not putting the things clearly. Thing is that

Assume I have two entities A and B and N:N relationship exists between them. Relation ship name should go in “Relation Name” property but

Related Entity -> A
RelationshipEntity -> B. Does this order really matters?


Thanks
Ramakrishna Sannidi

**Comment by joshcampbell191** [comment]
Sorry, the image I previously uploaded contained the wrong information. Please ensure that you're using the "Relationship entity name" of your N-N relationship when providing the "Relationship Entity" parameter as per the following screenshot:

![Relationship Entity](https://user-images.githubusercontent.com/1784236/91457751-b4698d00-e852-11ea-80e5-563f4540530b.png)

> Also one question for which I am waiting for response. Sorry for not putting the things clearly. Thing is that Assume I have two entities A and B and N:N relationship exists between them. Relation ship name should go in “Relation Name” property but Related Entity -> A RelationshipEntity -> B. Does this order really matters?

If you're editing the form for entity A to include a tag picker component for entity B, then the "Related Entity" should be the logical name of entity B and the "Relationship Entity" should be the logical name of the relationship entity of the N-to-N relationship between entity A and entity B (see previous screenshot).

Joshua Campbell

**Comment by joshcampbell191** [comment]
@ram-sannidi I will be marking this issue as closed. If you feel like your question was unanswered, please re-open the issue. Thanks!

**Comment by girishbellani14** [comment]
Hi Josh,
I'm facing same issue 
configuration is correct as mentioned but value is removed once page is refreshed Please help on this.

**Comment by joshcampbell191** [comment]
Hello @girishbellani14,

It doesn't sound like your relationship is saving. 

Can you please share your configuration with me?

Thanks,
Joshua Campbell

**Comment by girishbellani14** [comment]
![Capture](https://user-images.githubusercontent.com/37544772/93513061-e5654b00-f942-11ea-83ba-0dee20cf3ed8.PNG)
Hi @joshcampbell191 ,
This is configuration 
Thanks for quick reply.

**Comment by joshcampbell191** [comment]
It appears that the "Relationship Entity" property is incorrect. 

Can you please share the properties of the m365_Tag relationship? @girishbellani14

**Comment by girishbellani14** [comment]
It is same as relationship entity name , i manually added that
and one thing i'm facing issue as 19th 
Sorry for bit mess @joshcampbell191 
I'm to see related records and able to select but after refresh the grid is empty.

**Comment by joshcampbell191** [comment]
@girishbellani14  Can you please share the relationship properties so I can get a better understanding of how your environment is configured?

**Comment by girishbellani14** [comment]
![Capture1](https://user-images.githubusercontent.com/37544772/93517331-f1540b80-f948-11ea-985c-2606b44b32cb.PNG)
@joshcampbell191

**Comment by joshcampbell191** [comment]
Can you please ensure that you're using a N-to-N type relationship between your entities?

**Comment by girishbellani14** [comment]
Yes it's n-n @joshcampbell191

**Comment by joshcampbell191** [comment]
Unfortunately, I can no longer see the configuration you used for the control. Can you please share it again?

**Comment by girishbellani14** [comment]
Is it possible to connect through teams/skype?
Configuration is as per documentation only
@joshcampbell191

**Comment by joshcampbell191** [comment]
Sorry for the delay @girishbellani14. I can make myself available next Wednesday if that works for you.

**Comment by ram-sannidi** [comment]
I can help Girish on Monday.

@Girish let me know your free time. I will try to help you.

Thanks
Ram

Thanks
Ram
________________________________

**Comment by joshcampbell191** [comment]
@ram-sannidi @girishbellani14 were you guys able to connect and resolve the issue?

**Comment by ram-sannidi** [comment]
Hi,

No. I have not received any response from Girish.


Thanks
Ram
________________________________
