### ISSUE TITLE
I cannot find a managed zip file for import

### ISSUE THREAD

**Issue by malkhawaja** [opc-cpvp/OPC.PowerApps.PCFControls#854]
Hi,
is there a ready to install managed solution file? I do not know how to build the pcf from the code!

thanks

**Comment by joshcampbell191** [comment]
Hello @malkhawaja,

You can find the latest version of the managed / un-managed solution at the following URL: https://github.com/opc-cpvp/OPC.PowerApps.PCFControls/releases/tag/1.0.436

It appears that our build pipeline didn't correctly upload the solution files in the latest release.

**Comment by malkhawaja** [comment]
Huge thanks... really appreciate it.
