### ISSUE TITLE
it does not add new tags!

### ISSUE THREAD

**Issue by malkhawaja** [opc-cpvp/OPC.PowerApps.PCFControls#855]
after setting up the components, I tried both the field component and the grid component, but my problem with it that it does not add a new (not previously existing tag) to the Tags table, it only searched for existing tags and then relates them to the current record.

is this behaviour expected? I wish if it has the capability to add new tags records immediately upon hitting enter!

thanks.

**Comment by joshcampbell191** [comment]
Please note that this is the intended behaviour for these components. It simply serves as a method to associate records (many-to-many) to each other.
