### ISSUE TITLE
tagData: string is not assignable to type 'IOutputs'

### ISSUE THREAD

**Issue by walcivar** [opc-cpvp/OPC.PowerApps.PCFControls#862]
In getOutputs method I'm getting this issue:

Type '{ tagData: string; }' is not assignable to type 'IOutputs'.
  Object literal may only specify known properties, and 'tagData' does not exist in type 'IOutputs'

**Comment by joshcampbell191** [comment]
Hello @walcivar, are you attempting to build the project from sources?

**Comment by walcivar** [comment]
Hi @joshcampbell191 yes, but I have already solved this issue, what I don't know is how to configure it in the form. The documentation is not the best to understand the configuration, could you help me to understand at least what I have to put in the required parameters please? In my case I have a many to many relationship between Lead and a custom entity.

**Comment by walcivar** [comment]
I close this issue because now I have another issue related to PCF configuration
